apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-stg
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: matt.dekrey@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - http01:
        ingress:
          class: nginx