name: PR Review
on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

env:
  azClusterName: TinyKubed
  azClusterResourceGroup: DeKreyDotNet

  registryLoginServer: 'dekreydotnet.azurecr.io'
  imageName: 'dekreydotnet'
  k8sNamespacePrefix: 'dekrey-dot-net-pr-'
  releaseName: 'pr'

# Secrets generated via ./deployment/generate-credentials.ps1 - need to be reset regularly

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Log in to docker registry'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.registryLoginServer }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build and push image'
      run: |
        docker build . -t $registryLoginServer/$imageName:${{ github.sha }} --build-arg DOMAIN=https://pr-${{ github.event.pull_request.number }}.dekrey.net --build-arg GIT_HASH=${{ github.sha }}
        docker push $registryLoginServer/$imageName:${{ github.sha }}
      working-directory: ./ui

    # Set the target Azure Kubernetes Service (AKS) cluster.
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/aks-set-context@v2.0
      with:
        cluster-name: ${{ env.azClusterName }}
        resource-group: ${{ env.azClusterResourceGroup }}

    - name: Helm tool installer
      uses: Azure/setup-helm@v3
      with:
        version: 3.10.0

    - name: 'Deploy'
      run: |
        helm upgrade --install -n ${{ env.k8sNamespacePrefix }}${{ github.event.pull_request.number }} $releaseName --create-namespace --repo https://mdekrey.github.io/helm-charts single-container --set-string "image.repository=$registryLoginServer/$imageName,image.tag=${{ github.sha }},ingress.hosts[0].host=pr-${{ github.event.pull_request.number }}.dekrey.net" --values ./deployment/values.yaml

    - name: Report PR url
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Branch ready for preview at https://pr-${{ github.event.pull_request.number }}.dekrey.net'
          })
